version: '3.7'
services:
  mysql:
    restart: always
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: youtube
      MYSQL_USER: parser
      MYSQL_PASSWORD: secret

  parser:
    restart: always
    build:
      context: ./parser
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app/logs/
    environment:
      PYTHONIOENCODING: utf-8
      MYSQLHOST: mysql
      MYSQLUSER: parser
      MYSQLPASS: secret
      MYSQLDB: youtube
    ports:
      - 80:8000
    expose:
      - 8000
    depends_on:
      - mysql
